## Healthcheck
GET http://localhost:8000/healthcheck

###

## user creation
POST http://localhost:8000/api/users HTTP/1.1
User-Agent: rest-client
Content-Type: application/json

{
    "name": "Rishabh Anand",
    "email": "ranand16@gmail.com",
    "password": "qwerty1234",
    "passwordConfirmation": "qwerty1234"
}